### ISSUE TITLE
Installation instructions : software.opensuse.org

### ISSUE THREAD

**Issue by thomaslepoix** [ra3xdh/ra3xdh.github.io#2]
Hi Vadim,

Just to suggest you to redirect to this sole link in this website and Github releases instead of the raw repository link with hand-made instructions for each distro :
https://software.opensuse.org/download.html?project=home%3Ara3xdh&package=qucs-s

Note : AppImage are not accessible from there, it is a [bug](https://github.com/openSUSE/software-o-o/issues/171) that should be fixed one day.

**Comment by ra3xdh** [comment]
Hello Thomas,
thanks for pointing this. I didn't know about this possibility. I have just updated the installation instructions on the Qucs-S website.
